// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7M2EesCmUFXF5sSB8YKwZjWLPr5oDOxo',
    appId: '1:1080285334681:web:9e09c88d008038587a7c08',
    messagingSenderId: '1080285334681',
    projectId: 'project-86af5',
    authDomain: 'project-86af5.firebaseapp.com',
    storageBucket: 'project-86af5.appspot.com',
    measurementId: 'G-F4Y812MZHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQOzdf8vIpCwG8GWWLr3Ks-tzIXNSU70E',
    appId: '1:1080285334681:android:410077225a21de987a7c08',
    messagingSenderId: '1080285334681',
    projectId: 'project-86af5',
    storageBucket: 'project-86af5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNtsSBHfXJpg2qwU6OGc0saptxiB94ACE',
    appId: '1:1080285334681:ios:4a0a43063c3257587a7c08',
    messagingSenderId: '1080285334681',
    projectId: 'project-86af5',
    storageBucket: 'project-86af5.appspot.com',
    iosClientId: '1080285334681-k34l7mk9fut3t6erg322sca30onctd7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNtsSBHfXJpg2qwU6OGc0saptxiB94ACE',
    appId: '1:1080285334681:ios:4a0a43063c3257587a7c08',
    messagingSenderId: '1080285334681',
    projectId: 'project-86af5',
    storageBucket: 'project-86af5.appspot.com',
    iosClientId: '1080285334681-k34l7mk9fut3t6erg322sca30onctd7n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
